In [5]:
# Consider the below code to answer further questions:

import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

#### Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

* An array is a data structure that holds fix number of elements and these elements should be of the same data type. Most of the data structure makes use of an array to implement their algorithm. There is two important part of the array: one is an Element: Each item store in the array is called an element and second is an Index: Every element in the array has its own numerical value to identify the element.

* the list is written as the list of commas separated values inside the square bracket. The most important advantage of the list is the elements inside the list is not compulsorily be of the same data type along with negative indexing. Also, all the operation of the string is similarly applied on list data type such as slicing, concatenation, etc. Also, we can create the nested list i.e list containing another list.

In [9]:
# example of array.  
import array 
arr =np.array(list_)
  
np.asarray(list_)

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [12]:
# creating a list of items with different data types 
list_ = [ ['1' , '2'] , ['3' , '4' , '5' ] ] 
print(list_)

[['1', '2'], ['3', '4', '5']]


***
#### Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [18]:
import numpy as np

# creating and initializing array of string
arr_1 = np.array([ '1' , '2' , '3' , '4' , '5' ])

# printing array and its datatype
print('Array:', arr_1)

print('Datatype:', arr_1.dtype)


Array: ['1' '2' '3' '4' '5']
Datatype: <U1


In [25]:
import numpy as np

# creating and initializing array of string
arr_1 = np.array([ ['1' , '2'] , ['3' , '4' , '5' ] ])
(object==list_)
# printing array and its datatype
print('Array:', arr_1)

print('Datatype:', arr_1.dtype)

Array: [list(['1', '2']) list(['3', '4', '5'])]
Datatype: object


/tmp/ipykernel_77/3216279558.py:4: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr_1 = np.array([ ['1' , '2'] , ['3' , '4' , '5' ] ])


****
#### Q3. Considering the following changes in the variable, array_list

array_list = np.array(object = list_, dtype = int)


In [3]:
# Convert a Python list to a NumPy array
import numpy as np

# Create a Python list of integers
list_ = [1, 2, 3, 4, 5]

# Create a NumPy array from the Python list
array_list = np.array(object=list_, dtype=int)

print(array_list)

[1 2 3 4 5]


****


* Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list. Consider the below code to answer further questions

 import numpy as np 
 num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ] 
 num_array = np.array(object = num_list)

In [3]:
import numpy as np 
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ] 
num_array = np.array(object = num_list)

#### Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape

(ii) size

In [8]:
import numpy as np
 
arr = np.array( [[ 1, 2, 3],
                 [ 4, 5, 6]] )
 
print("Array is of type: ", type(arr))
 
print("No. of dimensions: ", arr.ndim)
 
print("Shape of array: ", arr.shape)
 
print("Array stores elements of type: ", arr.dtype)

Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  2
Shape of array:  (2, 3)
Array stores elements of type:  int64


In [7]:
# size
import numpy as np
x = np.array([ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ] )

print("Size of the array: ",
	x.size)

print("Memory size of one array element in bytes: ",
	x.itemsize)
print("Memory size of numpy array in bytes:",
	x.size * x.itemsize)


Size of the array:  6
Memory size of one array element in bytes:  8
Memory size of numpy array in bytes: 48


****

#### Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [19]:
# Python Program to create array with all zeros
import numpy as np

b = np.zeros([3, 3], dtype = int)
print("\nMatrix b : \n", b)



Matrix b : 
 [[0 0 0]
 [0 0 0]
 [0 0 0]]


****

#### Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [20]:
import numpy as np
x = np.diag([1, 2, 3, 4, 5])
print(x)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


****